### ISSUE TITLE
Move tests from Mocha to Qunit

### ISSUE THREAD

**Issue by kobsy** [cph/ember-list-keyboard-navigator#100]
Ember Mocha seems effectively abandoned, which means we can't update various packages to address CVEs. Qunit seems to be what the Ember community has settled on for testing, and as much as it's a pain to re-write our tests (again), it's better our tests have a future rather than being stuck on an ancient version of a testing framework.

**Comment by ghost** [comment]
My organization drifts along in a similar boat.
I found a codemod but cannot vouch for its quality: https://github.com/SaladFork/ember-mocha-to-qunit-codemod

**Comment by ghost** [comment]
Looks like this one too: https://github.com/freshworks/ember-freshdesk-codemods/blob/master/transforms/mocha-to-qunit/README.md
